### ISSUE TITLE
Error when running preview

### ISSUE THREAD

**Issue by VitaliiK91** [e111077/vite-lit-element-ts-sass#3]
Setup works when I run with `vite` command. However when I build and run `vite preview` I get the error 
`TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet`
In the bundled js file, it injects css style without wrapping in lit css
```
l.styles=":host {\n  display: block;\n  border: solid 1px gray;\n  padding: 16px;\n  max-width: 800px;\n```

Note I had to remove `lib` node from vite config to run no in library mode.
Thanks!

**Comment by e111077** [comment]
It seems outside of library mode the `vite:css-post` plugin runs in a different order.

might simply be able to do the following in the meantime:

- remove the `typings` directory
- set your styles as the following:

```ts
import {unsafeCSS} from 'lit';
import styles from './my-el.scss';

...

static styles = unsafeCSS(styles);
```

This should be fine now that it has been optimized in the following cl (might want to make sure the installed version of lit is updated to the newest Release Candidate):

https://github.com/lit/lit/pull/1857

Not ideal, but I'll have to keep looking to see how to hook into this vite plugin as the team's told me this is somewhere where they don't want people poking around.

**Comment by e111077** [comment]
fix is out for review at:

umbopepato/rollup-plugin-postcss-lit#41

**Comment by VitaliiK91** [comment]
Hi @e111077 , thanks for getting back so quick. I am trying to use the postcss with the fix you added. I cloned the repo and update package.json to `"rollup-plugin-postcss-lit": "e111077/rollup-plugin-postcss-lit#vite-default-export-support",`
But now when I try to build or serve I get the error:
```
$ vite
failed to load config from C:\Git\vite-lit-element-ts-sass\vite.config.ts
error when starting dev server:
TypeError: defaultLoader is not a function
    at Object.require.extensions.<computed> [as .ts] (C:\Git\vite-lit-element-ts-sass\node_modules\vite\dist\node\chunks\dep-e9a16784.js:70267:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Git\vite-lit-element-ts-sass\vite.config.ts:30:51)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.require.extensions.<computed> [as .ts] (C:\Git\vite-lit-element-ts-sass\node_modules\vite\dist\node\chunks\dep-e9a16784.js:70264:20)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)```

**Comment by VitaliiK91** [comment]
My bad. Forget to build the package. Works as expected. Thanks!

**Comment by VitaliiK91** [comment]
This issue was resolved with updated postcss-lit rollup plugin. 
However I just tested in vite version 2.3.4 and it fails as for some reason in preview, all style imports passed to postlit-css plugin are empty strings

**Comment by e111077** [comment]
\>.>

I'm going on an extended vacation, but will definitely take a look at this when I'm back. Do gotta say that the Vite team did say they didn't really want people playing around with their Sass loader so I think we might have to just expect breakages now and then until they provide a dedicated way to hook into it

**Comment by miwucs** [comment]
Hi, what's the status of this? I've tried updating to the latest version of rollup-plugin-postcss-lit (2.0.0) but I'm still running into the same `Uncaught TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.` error when running `vite build` then `vite preview`.

I'm not in "library mode" (I'm building an app, not just a component). My vite.config.ts is just

```
import {defineConfig} from 'vite';
import litcss from 'rollup-plugin-postcss-lit';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    {
      ...litcss(),
      enforce: 'post',
    },
  ],
});
```

Am I missing something? In the meantime the `unsafeCSS` trick is not very pretty but it does work!

**Comment by web-padawan** [comment]
For anyone who faces this problem, the workaround is described in this issue: https://github.com/umbopepato/rollup-plugin-postcss-lit/issues/49

**Comment by e111077** [comment]
I've updated the template to latest example template from vite 3. I also dropped rollup-plugin-postcss-lit since they've added `?inline` support. `unsafeCSS` should be all you need here. We've also made sure the performance of it should be up to par with normal `css` tagged template.

Also in `vite.config.ts` I've added two builds, one for a sharable lit library and another one for apps. Since Lit is just JS/TS the App config is literally `{}`. The library config tries to follow [this](https://justinfagnani.com/2019/11/01/how-to-publish-web-components-to-npm/) is best as possible (until esbuild can support `importHelpers`)
